# Generated by Django 3.0.8 on 2020-07-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cost', models.CharField(max_length=120)),
                ('loaction', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
            ],
        ),
    ]
