# Generated by Django 3.0.8 on 2020-07-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='image',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
