# Generated by Django 3.0.8 on 2020-07-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_toolbox', '0002_toolbox_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolbox',
            old_name='loaction',
            new_name='location',
        ),
    ]
